language: c

os: "linux"
dist: "trusty"
sudo: required

addons:
  apt:
    packages:
      - libqt4-dev

install:
  - sudo mkdir /tmp/install
  - tar xvf sip-4.18.1.tar.gz
  - cd sip-4.18.1
  - python3 configure.py
  - make
  - sudo make install
  - sudo make install DESTDIR=/tmp/install
  - cd ..
  - tar xvf PyQt-x11-gpl-4.11.4.tar.gz
  - cd PyQt-x11-gpl-4.11.4/
  - export PATH=$PATH:/tmp/install/usr/bin
  - python3 configure-ng.py --confirm-license -b /tmp/install/usr/bin/ -d /tmp/install/usr/lib/python3/dist-packages/ -v /tmp/install/share/sip/PyQt4
  - make
  - sudo make install
  - gem install fpm
